# Generated by Django 2.2.7 on 2019-11-30 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name Stock')),
                ('origin_farm', models.CharField(max_length=100, verbose_name='Origin Famr')),
                ('quantity_bags_availible', models.IntegerField()),
                ('stock_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('expirate_date', models.DateField()),
                ('quantity_bags', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type_coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
