# Generated by Django 2.2.7 on 2019-11-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191130_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='coffee_types',
        ),
        migrations.AddField(
            model_name='coffeebag',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
            preserve_default=False,
        ),
    ]
