# Generated by Django 2.2.7 on 2019-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191130_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_bags_availible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
