# Generated by Django 2.2.7 on 2019-11-30 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20191130_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeebag',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffees_types', to='core.Stock'),
        ),
    ]
